# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      nombres: "Andrea Isabel"        
      apellidos: "Sotil Lozada"     
      edad: "30"      
      version_proyecto: "3.0"             

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # PRIMER STEP: PRESENTACIÓN
      - name: presentación          # 1er step
        run: |
          echo "Nombres: $nombres"
          echo "Apellidos: $apellidos"
          echo "Edad: $edad"

    # SEGUNDO STEP
      - name: datos generales       # 2do step
        run: |
          echo "Carrera de Ingeniería de Sistemas"

      - name: Variables de entorno secretas   # 3er step
        env:
          USER_SECRET: ${{ secrets.USER_SECRET }}
          PASSWORD_SECRET: ${{ secrets.PASSWORD_SECRET }}
        run: |
          echo "user: $USER_SECRET"
          echo "password: $PASSWORD_SECRET"

      - name: variables abiertas    # 4to step
        run: |
          echo "versión de mi proyecto: $version_proyecto"

  
